# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  name: My Computer
  vmImage: windows-latest

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
  - task: Cache@2

  - script: |
      pnpm install
    displayName: Installing apps

  - script: |
      pnpm build
    displayName: Building apps

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/.output
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
      replaceExistingArchive: true
    displayName: Archiving build files

  - task: SSH@0
    inputs:
      sshEndpoint: Ella
      runOptions: commands
      commands: 'cd ~/apps/jkt48showroom/.output && rm -r *'
      readyTimeout: '20000'
    continueOnError: true
    displayName: Deleting old files

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: Ella
      sourceFolder: $(Build.ArtifactStagingDirectory)
      contents: app.zip
      targetFolder: ~/apps/jkt48showroom/.output
      cleanTargetFolder: true
      cleanHiddenFilesInTarget: true
      readyTimeout: '20000'
    displayName: Transfer build files to server

  - task: SSH@0
    inputs:
      sshEndpoint: Ella
      runOptions: commands
      commands: 'cd ~/apps/jkt48showroom/.output && unzip app.zip && pm2 restart 1'
      readyTimeout: '20000'
    displayName: Run deployed apps
