name: Vercel Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: nexterias/actions-vercel@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ vars.VERCEL_ORG_ID }}
          project-id: ${{ vars.VERCEL_PROJECT_ID }}
          production: ${{ github.ref == 'refs/heads/master' }}
          # prebuilt: true # If set to true, build will be performed using GitHub Actions.
